In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv(r"C:\Users\mpkhd\Desktop\Uni\4th year\Sem1\ST4052\Project1\recruitment_data.csv")

In [3]:
df.head()

,Age,Gender,EducationLevel,ExperienceYears,PreviousCompanies,DistanceFromCompany,InterviewScore,SkillScore,PersonalityScore,RecruitmentStrategy,HiringDecision
0,26,1,2,0,3,26.783828,48,78,91,1,1
1,39,1,4,12,3,25.862694,35,68,80,2,1
2,48,0,2,3,2,9.920805,20,67,13,2,0
3,34,1,2,5,2,6.407751,36,27,70,3,0
4,30,0,1,6,1,43.105343,23,52,85,2,0

In [7]:
#df.describe()
df.shape

(1500, 11)

In [9]:
df["HiringDecision"][(df["HiringDecision"] == 1)].count()

465

In [11]:
colnames = df.columns
colnames.shape

(11,)

In [13]:
X = pd.DataFrame()
y = pd.DataFrame()

In [15]:
for i in colnames:
    if i != "HiringDecision":
        X[i] = df[i]
    else:
        y[i] = df[i]

In [17]:
X.head()

,Age,Gender,EducationLevel,ExperienceYears,PreviousCompanies,DistanceFromCompany,InterviewScore,SkillScore,PersonalityScore,RecruitmentStrategy
0,26,1,2,0,3,26.783828,48,78,91,1
1,39,1,4,12,3,25.862694,35,68,80,2
2,48,0,2,3,2,9.920805,20,67,13,2
3,34,1,2,5,2,6.407751,36,27,70,3
4,30,0,1,6,1,43.105343,23,52,85,2

In [19]:
y.head()

   HiringDecision
0               1
1               1
2               0
3               0
4               0

In [135]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

In [153]:
train = pd.concat([X_train,y_train],axis = 1)

In [155]:
test = pd.concat([X_test,y_test],axis = 1)

In [ ]:
train.to_csv('my_file.csv', index=False)